# @package _global_
model:
  name: 
  dropout_rate:
  batch_size: 
  dim_treatments: ???               # Will be defined with +dataset=...
  dim_covariate: ???                # Will be defined with +dataset=...
  dim_static_features: ???          # Will be defined with +dataset=...
  dim_outcomes: ???                 # Will be defined with +dataset=...
  max_grad_norm:
  num_layer: 1
  hidden_dim: 32
  input_dim:
  output_dim:
  optimizer:
    optimizer_cls: adam
    learning_rate: 0.01
    weight_decay: 0.0
    lr_scheduler: False

exp:
  seed: 42                          # Random seed for all the initialisations, dataset generation etc.
  gpus: [0]                         # Number of GPUs to use / indices of GPUs like [0,1]
  max_epochs: 200                   # Number of epochs
  projection_horizon:

# Dataset for training / evaluation -- specific values should be filled for each dataset
dataset:
  data_type:
  val_batch_size: ???               # Will be defined with +dataset=...
  has_covariate: False
